// <auto-generated />
using System;
using GymManager.DbModels.Engines;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymManager.Migrations.Sqlite
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20221130094145_2022-11-30")]
    partial class _20221130
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("GymManager.DbModels.CabinetKey", b =>
                {
                    b.Property<int>("CabinetKeyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GenderID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUsedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CabinetKeyID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("GenderID");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CabinetKeys");
                });

            modelBuilder.Entity("GymManager.DbModels.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxIdNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("GymManager.DbModels.DataTracking", b =>
                {
                    b.Property<int>("DataTrackingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataTrackingOperationID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryKey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("DataTrackingID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DataTrackingOperationID");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("DataTrackings");
                });

            modelBuilder.Entity("GymManager.DbModels.DataTrackingDefinition", b =>
                {
                    b.Property<int>("DataTrackingDefinitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColumnName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataTrackingID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DataTrackingDefinitionID");

                    b.HasIndex("DataTrackingID");

                    b.ToTable("DataTrackingDefinitions");
                });

            modelBuilder.Entity("GymManager.DbModels.DataTrackingOperation", b =>
                {
                    b.Property<int>("DataTrackingOperationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("DataTrackingOperationID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DataTrackingOperations");

                    b.HasData(
                        new
                        {
                            DataTrackingOperationID = 1,
                            Name = "DODAWANIE"
                        },
                        new
                        {
                            DataTrackingOperationID = 2,
                            Name = "EDYTOWANIE"
                        },
                        new
                        {
                            DataTrackingOperationID = 3,
                            Name = "USUWANIE"
                        });
                });

            modelBuilder.Entity("GymManager.DbModels.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GenderID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pesel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("GenderID");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("GymManager.DbModels.EntryRegistry", b =>
                {
                    b.Property<int>("EntryRegistryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CabinetKeyID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PassID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VisitTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntryRegistryID");

                    b.HasIndex("CabinetKeyID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("PassID");

                    b.ToTable("EntriesRegistry");
                });

            modelBuilder.Entity("GymManager.DbModels.Gender", b =>
                {
                    b.Property<int>("GenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GenderID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderID = 1,
                            Name = "NIE PODANO"
                        },
                        new
                        {
                            GenderID = 2,
                            Name = "MĘŻCZYZNA"
                        },
                        new
                        {
                            GenderID = 3,
                            Name = "KOBIETA"
                        });
                });

            modelBuilder.Entity("GymManager.DbModels.GymObject", b =>
                {
                    b.Property<int>("GymObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("GymObjectID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("GymObjects");
                });

            modelBuilder.Entity("GymManager.DbModels.Identifier", b =>
                {
                    b.Property<int>("IdentifierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaCarrierID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdentifierID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("MediaCarrierID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Identifiers");
                });

            modelBuilder.Entity("GymManager.DbModels.MediaCarrier", b =>
                {
                    b.Property<int>("MediaCarrierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MediaCarrierID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MediaCarriers");

                    b.HasData(
                        new
                        {
                            MediaCarrierID = 1,
                            IsAcive = true,
                            Name = "KARTA RFID"
                        });
                });

            modelBuilder.Entity("GymManager.DbModels.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GenderID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PassID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pesel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MemberID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("GenderID");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("PassID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("GymManager.DbModels.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageTypeID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("MessageTypeID");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("GymManager.DbModels.MessageRegistry", b =>
                {
                    b.Property<int>("MessageRegistryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailSentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsError")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageContnet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SmsSentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageRegistryID");

                    b.HasIndex("MemberID");

                    b.HasIndex("MessageID");

                    b.ToTable("MessagesRegistry");
                });

            modelBuilder.Entity("GymManager.DbModels.MessageType", b =>
                {
                    b.Property<int>("MessageTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MessageTypeID");

                    b.ToTable("MessageTypes");
                });

            modelBuilder.Entity("GymManager.DbModels.Pass", b =>
                {
                    b.Property<int>("PassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AccessTimeFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AccessTimeTo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AskAddEntry")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Continuation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EentryNumberOfMonths")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EntryNetPrice")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("PassTimeID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("TaxID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PassID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PassTimeID");

                    b.HasIndex("TaxID");

                    b.ToTable("Passes");

                    b.HasData(
                        new
                        {
                            PassID = 1,
                            AddedBy = 1,
                            Continuation = true,
                            DateAdded = new DateTime(2022, 11, 30, 10, 41, 45, 545, DateTimeKind.Local).AddTicks(9578),
                            Description = "",
                            EentryNumberOfMonths = 1,
                            EntryNetPrice = 0m,
                            EntryPrice = 0m,
                            IsAcive = true,
                            Name = "BRAK",
                            NetPrice = 0m,
                            PassTimeID = 5,
                            Price = 0m,
                            TaxID = 4
                        },
                        new
                        {
                            PassID = 2,
                            AddedBy = 1,
                            Continuation = true,
                            DateAdded = new DateTime(2022, 11, 30, 10, 41, 45, 545, DateTimeKind.Local).AddTicks(9582),
                            Description = "Wstpęp wolny na miesiąc",
                            EentryNumberOfMonths = 1,
                            EntryNetPrice = 20.00m,
                            EntryPrice = 18.52m,
                            IsAcive = true,
                            Name = "OPEN",
                            NetPrice = 100.93m,
                            PassTimeID = 3,
                            Price = 109.00m,
                            TaxID = 2
                        },
                        new
                        {
                            PassID = 3,
                            AccessTimeFrom = new DateTime(2000, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessTimeTo = new DateTime(2000, 1, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = 1,
                            Continuation = true,
                            DateAdded = new DateTime(2022, 11, 30, 10, 41, 45, 545, DateTimeKind.Local).AddTicks(9589),
                            Description = "Wstpęp wolny w godz. 9-14 na miesiąc",
                            EentryNumberOfMonths = 1,
                            EntryNetPrice = 20.00m,
                            EntryPrice = 18.52m,
                            IsAcive = true,
                            Name = "OPEN PORANNY",
                            NetPrice = 73.15m,
                            PassTimeID = 3,
                            Price = 79.00m,
                            TaxID = 2
                        },
                        new
                        {
                            PassID = 4,
                            AddedBy = 1,
                            Continuation = true,
                            DateAdded = new DateTime(2022, 11, 30, 10, 41, 45, 545, DateTimeKind.Local).AddTicks(9590),
                            Description = "Wstpęp wolny dla studentów",
                            EentryNumberOfMonths = 1,
                            EntryNetPrice = 0m,
                            EntryPrice = 0m,
                            IsAcive = true,
                            Name = "STUDENT",
                            NetPrice = 91.67m,
                            PassTimeID = 3,
                            Price = 99.00m,
                            TaxID = 2
                        },
                        new
                        {
                            PassID = 5,
                            AddedBy = 1,
                            Continuation = true,
                            DateAdded = new DateTime(2022, 11, 30, 10, 41, 45, 545, DateTimeKind.Local).AddTicks(9592),
                            Description = "Wstpęp wolny na miesiąc",
                            EentryNumberOfMonths = 1,
                            EntryNetPrice = 0m,
                            EntryPrice = 0m,
                            IsAcive = true,
                            Name = "PROMOCJA LUTY2022",
                            NetPrice = 91.67m,
                            PassTimeID = 3,
                            Price = 99.00m,
                            TaxID = 2
                        },
                        new
                        {
                            PassID = 6,
                            AddedBy = 1,
                            Continuation = true,
                            DateAdded = new DateTime(2022, 11, 30, 10, 41, 45, 545, DateTimeKind.Local).AddTicks(9594),
                            Description = "Wstpęp jednorazowy",
                            EentryNumberOfMonths = 1,
                            EntryNetPrice = 0m,
                            EntryPrice = 0m,
                            IsAcive = true,
                            Name = "JEDNORAZOWY",
                            NetPrice = 18.52m,
                            PassTimeID = 3,
                            Price = 20.00m,
                            TaxID = 2
                        });
                });

            modelBuilder.Entity("GymManager.DbModels.PassRegistry", b =>
                {
                    b.Property<int>("PassRegistryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Continuation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndSuspensionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartSuspensionDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Suspension")
                        .HasColumnType("INTEGER");

                    b.HasKey("PassRegistryID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("MemberID");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("PassID");

                    b.ToTable("PassesRegistry");
                });

            modelBuilder.Entity("GymManager.DbModels.PassTime", b =>
                {
                    b.Property<int>("PassTimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PassTimeID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PassTimes");

                    b.HasData(
                        new
                        {
                            PassTimeID = 1,
                            Name = "Dzień"
                        },
                        new
                        {
                            PassTimeID = 2,
                            Name = "Tydzień"
                        },
                        new
                        {
                            PassTimeID = 3,
                            Name = "Miesiąć"
                        },
                        new
                        {
                            PassTimeID = 4,
                            Name = "Rok"
                        },
                        new
                        {
                            PassTimeID = 5,
                            Name = "Nieskonczony"
                        });
                });

            modelBuilder.Entity("GymManager.DbModels.PermissionList", b =>
                {
                    b.Property<int>("PermissionListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PermissionListID");

                    b.HasIndex("Name");

                    b.ToTable("PermissionsList");

                    b.HasData(
                        new
                        {
                            PermissionListID = 1,
                            Name = "DOSTĘP CZŁONKOWIE"
                        },
                        new
                        {
                            PermissionListID = 2,
                            Name = "DODAWANIE CZŁONKÓW"
                        },
                        new
                        {
                            PermissionListID = 3,
                            Name = "EDYCJA CZŁONKÓW"
                        },
                        new
                        {
                            PermissionListID = 4,
                            Name = "USWANIE CZŁONKÓW"
                        },
                        new
                        {
                            PermissionListID = 5,
                            Name = "DOSTĘP KARNETY CZŁONKOW"
                        },
                        new
                        {
                            PermissionListID = 6,
                            Name = "DODAWANIE KARNETÓW CZŁONKÓW"
                        },
                        new
                        {
                            PermissionListID = 7,
                            Name = "EDYCJA KARNETÓW CZŁONKÓW"
                        },
                        new
                        {
                            PermissionListID = 8,
                            Name = "USWANIE KARNETÓW CZŁONKÓW"
                        },
                        new
                        {
                            PermissionListID = 9,
                            Name = "DOSTĘP KLCUZE"
                        },
                        new
                        {
                            PermissionListID = 10,
                            Name = "DODAWANIE KLUCZY"
                        },
                        new
                        {
                            PermissionListID = 11,
                            Name = "EDYCJA KLUCZY"
                        },
                        new
                        {
                            PermissionListID = 12,
                            Name = "USWANIE KLUCZY"
                        },
                        new
                        {
                            PermissionListID = 13,
                            Name = "DOSTĘP KARNETY"
                        },
                        new
                        {
                            PermissionListID = 14,
                            Name = "DODAWANIE KARNETÓW"
                        },
                        new
                        {
                            PermissionListID = 15,
                            Name = "EDYCJA KARNETÓW"
                        },
                        new
                        {
                            PermissionListID = 16,
                            Name = "USWANIE KARNETÓW"
                        },
                        new
                        {
                            PermissionListID = 17,
                            Name = "DOSTĘP UŻYTKOWNICY"
                        },
                        new
                        {
                            PermissionListID = 18,
                            Name = "DODAWANIE UŻYTKOWNKÓW"
                        },
                        new
                        {
                            PermissionListID = 19,
                            Name = "EDYCJA UŻYTKOWNKÓW"
                        },
                        new
                        {
                            PermissionListID = 20,
                            Name = "USWANIE UŻYTKOWNKÓW"
                        },
                        new
                        {
                            PermissionListID = 21,
                            Name = "DOSTĘP OSOBY W OBIEKCIE"
                        },
                        new
                        {
                            PermissionListID = 22,
                            Name = "DOSTĘP WIADOMOŚCI"
                        },
                        new
                        {
                            PermissionListID = 23,
                            Name = "DOSTĘP REJESTR WEJŚĆ"
                        },
                        new
                        {
                            PermissionListID = 24,
                            Name = "DOSTĘP REJESTR OPERACJI"
                        },
                        new
                        {
                            PermissionListID = 25,
                            Name = "DOSTĘP USTAWIENIA"
                        },
                        new
                        {
                            PermissionListID = 26,
                            Name = "ZAMYKANIE WEJŚCIA CZŁONKÓW W OBIEKCIE"
                        },
                        new
                        {
                            PermissionListID = 27,
                            Name = "DODAJ WEJŚCIE/WYJŚCIE BEZ IDENTYFIKATORA"
                        });
                });

            modelBuilder.Entity("GymManager.DbModels.PermissionUser", b =>
                {
                    b.Property<int>("PermissionUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int>("PermissionListID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PermissionUserID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("PermissionListID");

                    b.HasIndex("UserID");

                    b.ToTable("PermissionsUsers");
                });

            modelBuilder.Entity("GymManager.DbModels.Photo", b =>
                {
                    b.Property<int>("PhotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INTEGER");

                    b.HasKey("PhotoID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("MemberID");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("GymManager.DbModels.Tax", b =>
                {
                    b.Property<int>("TaxID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rate")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaxID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Taxes");

                    b.HasData(
                        new
                        {
                            TaxID = 1,
                            DateAdded = new DateTime(2022, 11, 30, 10, 41, 45, 545, DateTimeKind.Local).AddTicks(9548),
                            IsAcive = true,
                            Name = "A",
                            Rate = 23
                        },
                        new
                        {
                            TaxID = 2,
                            DateAdded = new DateTime(2022, 11, 30, 10, 41, 45, 545, DateTimeKind.Local).AddTicks(9551),
                            IsAcive = true,
                            Name = "B",
                            Rate = 8
                        },
                        new
                        {
                            TaxID = 3,
                            DateAdded = new DateTime(2022, 11, 30, 10, 41, 45, 545, DateTimeKind.Local).AddTicks(9552),
                            IsAcive = true,
                            Name = "C",
                            Rate = 5
                        },
                        new
                        {
                            TaxID = 4,
                            DateAdded = new DateTime(2022, 11, 30, 10, 41, 45, 545, DateTimeKind.Local).AddTicks(9553),
                            IsAcive = true,
                            Name = "D",
                            Rate = 0
                        });
                });

            modelBuilder.Entity("GymManager.DbModels.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            DateAdded = new DateTime(2022, 11, 30, 10, 41, 45, 545, DateTimeKind.Local).AddTicks(9435),
                            FirstName = "Administrator",
                            IsAcive = true,
                            IsAdmin = true,
                            LastName = "systemu",
                            Password = "21232f297a57a5a743894a0e4a801fc3",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("GymManager.DbModels.CabinetKey", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID");

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("AddedByUser");

                    b.Navigation("Gender");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("GymManager.DbModels.Company", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("AddedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("GymManager.DbModels.DataTracking", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.DataTrackingOperation", "DataTrackingOperation")
                        .WithMany()
                        .HasForeignKey("DataTrackingOperationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("AddedByUser");

                    b.Navigation("DataTrackingOperation");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("GymManager.DbModels.DataTrackingDefinition", b =>
                {
                    b.HasOne("GymManager.DbModels.DataTracking", "DataTracking")
                        .WithMany()
                        .HasForeignKey("DataTrackingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataTracking");
                });

            modelBuilder.Entity("GymManager.DbModels.Employee", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID");

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("AddedByUser");

                    b.Navigation("Gender");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("GymManager.DbModels.EntryRegistry", b =>
                {
                    b.HasOne("GymManager.DbModels.CabinetKey", "CabinetKey")
                        .WithMany()
                        .HasForeignKey("CabinetKeyID");

                    b.HasOne("GymManager.DbModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("GymManager.DbModels.Pass", "Pass")
                        .WithMany()
                        .HasForeignKey("PassID");

                    b.Navigation("CabinetKey");

                    b.Navigation("Member");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Pass");
                });

            modelBuilder.Entity("GymManager.DbModels.GymObject", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("AddedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("GymManager.DbModels.Identifier", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.MediaCarrier", "MediaCarrier")
                        .WithMany()
                        .HasForeignKey("MediaCarrierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("AddedByUser");

                    b.Navigation("MediaCarrier");

                    b.Navigation("Member");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("GymManager.DbModels.Member", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID");

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("GymManager.DbModels.Pass", "Pass")
                        .WithMany()
                        .HasForeignKey("PassID");

                    b.Navigation("AddedByUser");

                    b.Navigation("Gender");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Pass");
                });

            modelBuilder.Entity("GymManager.DbModels.Message", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.MessageType", "MessageType")
                        .WithMany()
                        .HasForeignKey("MessageTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("AddedByUser");

                    b.Navigation("MessageType");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("GymManager.DbModels.MessageRegistry", b =>
                {
                    b.HasOne("GymManager.DbModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("GymManager.DbModels.Pass", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("GymManager.DbModels.PassTime", "PassTime")
                        .WithMany()
                        .HasForeignKey("PassTimeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.Tax", "Tax")
                        .WithMany()
                        .HasForeignKey("TaxID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("PassTime");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("GymManager.DbModels.PassRegistry", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("GymManager.DbModels.Pass", "Pass")
                        .WithMany()
                        .HasForeignKey("PassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Member");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Pass");
                });

            modelBuilder.Entity("GymManager.DbModels.PermissionUser", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.PermissionList", "PermissionList")
                        .WithMany()
                        .HasForeignKey("PermissionListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("PermissionList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymManager.DbModels.Photo", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("AddedByUser");

                    b.Navigation("Member");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("GymManager.DbModels.User", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("AddedByUser");

                    b.Navigation("ModifiedByUser");
                });
#pragma warning restore 612, 618
        }
    }
}
