// <auto-generated />
using System;
using GymManager.DbModels;
using GymManager.DbModels.Engines;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymManager.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20220129114815_2022-01-29")]
    partial class _20220129
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GymManager.DbModels.CabinetKey", b =>
                {
                    b.Property<int>("CabinetKeyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CabinetKeyID"), 1L, 1);

                    b.Property<int?>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GenderID")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CabinetKeyID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("GenderID");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CabinetKeys");
                });

            modelBuilder.Entity("GymManager.DbModels.DataTracking", b =>
                {
                    b.Property<int>("DataTrackingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DataTrackingID"), 1L, 1);

                    b.Property<int>("DataTrackingOperationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DataTrackingID");

                    b.HasIndex("DataTrackingOperationID");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("DataTrackings");
                });

            modelBuilder.Entity("GymManager.DbModels.DataTrackingDefinition", b =>
                {
                    b.Property<int>("DataTrackingDefinitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DataTrackingDefinitionID"), 1L, 1);

                    b.Property<int>("DataTrackingID")
                        .HasColumnType("int");

                    b.Property<string>("NewData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DataTrackingDefinitionID");

                    b.HasIndex("DataTrackingID");

                    b.ToTable("DataTrackingDefinitions");
                });

            modelBuilder.Entity("GymManager.DbModels.DataTrackingOperation", b =>
                {
                    b.Property<int>("DataTrackingOperationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DataTrackingOperationID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DataTrackingOperationID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DataTrackingOperations");

                    b.HasData(
                        new
                        {
                            DataTrackingOperationID = 1,
                            Name = "Dodanie"
                        },
                        new
                        {
                            DataTrackingOperationID = 2,
                            Name = "Edyja"
                        },
                        new
                        {
                            DataTrackingOperationID = 3,
                            Name = "Usuwanie"
                        });
                });

            modelBuilder.Entity("GymManager.DbModels.EntryRegistry", b =>
                {
                    b.Property<int>("EntryRegisterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntryRegisterID"), 1L, 1);

                    b.Property<int?>("CabinetKeyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("bit");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int?>("VisitTime")
                        .HasColumnType("int");

                    b.HasKey("EntryRegisterID");

                    b.HasIndex("CabinetKeyID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("EntriesRegistry");
                });

            modelBuilder.Entity("GymManager.DbModels.Gender", b =>
                {
                    b.Property<int>("GenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GenderID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderID = 1,
                            Name = "NIE PODANO"
                        },
                        new
                        {
                            GenderID = 2,
                            Name = "MĘŻCZYZNA"
                        },
                        new
                        {
                            GenderID = 3,
                            Name = "KOBIETA"
                        });
                });

            modelBuilder.Entity("GymManager.DbModels.Identifier", b =>
                {
                    b.Property<int>("IdentifierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentifierID"), 1L, 1);

                    b.Property<int?>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MediaCarrierID")
                        .HasColumnType("int");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.HasKey("IdentifierID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("MediaCarrierID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Identifiers");
                });

            modelBuilder.Entity("GymManager.DbModels.MediaCarrier", b =>
                {
                    b.Property<int>("MediaCarrierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaCarrierID"), 1L, 1);

                    b.Property<bool>("IsAcive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MediaCarrierID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MediaCarriers");

                    b.HasData(
                        new
                        {
                            MediaCarrierID = 1,
                            IsAcive = true,
                            Name = "KARTA RFID"
                        });
                });

            modelBuilder.Entity("GymManager.DbModels.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"), 1L, 1);

                    b.Property<int?>("AddedBy")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GenderID")
                        .HasColumnType("int");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int?>("PassID")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MemberID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("GenderID");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("PassID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("GymManager.DbModels.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"), 1L, 1);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSms")
                        .HasColumnType("bit");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<bool>("SmsSent")
                        .HasColumnType("bit");

                    b.Property<string>("TextMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageID");

                    b.HasIndex("MemberID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("GymManager.DbModels.Pass", b =>
                {
                    b.Property<int>("PassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassID"), 1L, 1);

                    b.Property<DateTime?>("AccessTimeFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AccessTimeTo")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedBy")
                        .HasColumnType("int");

                    b.Property<bool>("Continuation")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EntryNetPrice")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("PassTimeID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("TaxID")
                        .HasColumnType("int");

                    b.HasKey("PassID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PassTimeID");

                    b.HasIndex("TaxID");

                    b.ToTable("Passes");

                    b.HasData(
                        new
                        {
                            PassID = 1,
                            AddedBy = 1,
                            Continuation = true,
                            DateAdded = new DateTime(2022, 1, 29, 12, 48, 14, 862, DateTimeKind.Local).AddTicks(2214),
                            Description = "",
                            EntryNetPrice = 0m,
                            EntryPrice = 0m,
                            IsAcive = true,
                            Name = "BRAK",
                            NetPrice = 0m,
                            PassTimeID = 5,
                            Price = 0m,
                            TaxID = 4
                        },
                        new
                        {
                            PassID = 2,
                            AddedBy = 1,
                            Continuation = true,
                            DateAdded = new DateTime(2022, 1, 29, 12, 48, 14, 862, DateTimeKind.Local).AddTicks(2220),
                            Description = "Wstpęp wolny na miesiąc",
                            EntryNetPrice = 20.00m,
                            EntryPrice = 18.52m,
                            IsAcive = true,
                            Name = "OPEN",
                            NetPrice = 100.93m,
                            PassTimeID = 3,
                            Price = 109.00m,
                            TaxID = 2
                        },
                        new
                        {
                            PassID = 3,
                            AccessTimeFrom = new DateTime(2000, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessTimeTo = new DateTime(2000, 1, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = 1,
                            Continuation = true,
                            DateAdded = new DateTime(2022, 1, 29, 12, 48, 14, 862, DateTimeKind.Local).AddTicks(2228),
                            Description = "Wstpęp wolny w godz. 9-14 na miesiąc",
                            EntryNetPrice = 20.00m,
                            EntryPrice = 18.52m,
                            IsAcive = true,
                            Name = "OPEN PORANNY",
                            NetPrice = 73.15m,
                            PassTimeID = 3,
                            Price = 79.00m,
                            TaxID = 2
                        },
                        new
                        {
                            PassID = 4,
                            AddedBy = 1,
                            Continuation = true,
                            DateAdded = new DateTime(2022, 1, 29, 12, 48, 14, 862, DateTimeKind.Local).AddTicks(2230),
                            Description = "Wstpęp wolny dla studentów",
                            EntryNetPrice = 0m,
                            EntryPrice = 0m,
                            IsAcive = true,
                            Name = "STUDENT",
                            NetPrice = 91.67m,
                            PassTimeID = 3,
                            Price = 99.00m,
                            TaxID = 2
                        },
                        new
                        {
                            PassID = 5,
                            AddedBy = 1,
                            Continuation = true,
                            DateAdded = new DateTime(2022, 1, 29, 12, 48, 14, 862, DateTimeKind.Local).AddTicks(2233),
                            Description = "Wstpęp wolny na miesiąc",
                            EntryNetPrice = 0m,
                            EntryPrice = 0m,
                            IsAcive = true,
                            Name = "PROMOCJA LUTY2022",
                            NetPrice = 91.67m,
                            PassTimeID = 3,
                            Price = 99.00m,
                            TaxID = 2
                        },
                        new
                        {
                            PassID = 6,
                            AddedBy = 1,
                            Continuation = true,
                            DateAdded = new DateTime(2022, 1, 29, 12, 48, 14, 862, DateTimeKind.Local).AddTicks(2235),
                            Description = "Wstpęp jednorazowy",
                            EntryNetPrice = 0m,
                            EntryPrice = 0m,
                            IsAcive = true,
                            Name = "JEDNORAZOWY",
                            NetPrice = 18.52m,
                            PassTimeID = 3,
                            Price = 20.00m,
                            TaxID = 2
                        });
                });

            modelBuilder.Entity("GymManager.DbModels.PassRegistry", b =>
                {
                    b.Property<int>("PassRegistryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassRegistryID"), 1L, 1);

                    b.Property<int?>("AddedBy")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Continuation")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("PassID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PassRegistryID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("MemberID");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("PassID");

                    b.ToTable("PassesRegistry");
                });

            modelBuilder.Entity("GymManager.DbModels.PassTime", b =>
                {
                    b.Property<int>("PassTimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassTimeID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PassTimeID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PassTimes");

                    b.HasData(
                        new
                        {
                            PassTimeID = 1,
                            Name = "Dzień"
                        },
                        new
                        {
                            PassTimeID = 2,
                            Name = "Tydzień"
                        },
                        new
                        {
                            PassTimeID = 3,
                            Name = "Miesiąć"
                        },
                        new
                        {
                            PassTimeID = 4,
                            Name = "Rok"
                        },
                        new
                        {
                            PassTimeID = 5,
                            Name = "Nieskonczony"
                        });
                });

            modelBuilder.Entity("GymManager.DbModels.Tax", b =>
                {
                    b.Property<int>("TaxID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxID"), 1L, 1);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasKey("TaxID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Taxes");

                    b.HasData(
                        new
                        {
                            TaxID = 1,
                            DateAdded = new DateTime(2022, 1, 29, 12, 48, 14, 862, DateTimeKind.Local).AddTicks(2172),
                            IsAcive = true,
                            Name = "A",
                            Rate = 23
                        },
                        new
                        {
                            TaxID = 2,
                            DateAdded = new DateTime(2022, 1, 29, 12, 48, 14, 862, DateTimeKind.Local).AddTicks(2176),
                            IsAcive = true,
                            Name = "B",
                            Rate = 8
                        },
                        new
                        {
                            TaxID = 3,
                            DateAdded = new DateTime(2022, 1, 29, 12, 48, 14, 862, DateTimeKind.Local).AddTicks(2178),
                            IsAcive = true,
                            Name = "C",
                            Rate = 5
                        },
                        new
                        {
                            TaxID = 4,
                            DateAdded = new DateTime(2022, 1, 29, 12, 48, 14, 862, DateTimeKind.Local).AddTicks(2180),
                            IsAcive = true,
                            Name = "D",
                            Rate = 0
                        });
                });

            modelBuilder.Entity("GymManager.DbModels.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1L, 1);

                    b.Property<int?>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAcive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("ModifiedBy")
                        .IsUnique()
                        .HasFilter("[ModifiedBy] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            DateAdded = new DateTime(2022, 1, 29, 12, 48, 14, 862, DateTimeKind.Local).AddTicks(2031),
                            FirstName = "Administrator",
                            IsAcive = true,
                            IsAdmin = true,
                            LastName = "systemu",
                            Password = "21232f297a57a5a743894a0e4a801fc3",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("GymManager.DbModels.CabinetKey", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID");

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("AddedByUser");

                    b.Navigation("Gender");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("GymManager.DbModels.DataTracking", b =>
                {
                    b.HasOne("GymManager.DbModels.DataTrackingOperation", "DataTrackingOperation")
                        .WithMany()
                        .HasForeignKey("DataTrackingOperationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("DataTrackingOperation");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("GymManager.DbModels.DataTrackingDefinition", b =>
                {
                    b.HasOne("GymManager.DbModels.DataTracking", "DataTracking")
                        .WithMany()
                        .HasForeignKey("DataTrackingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataTracking");
                });

            modelBuilder.Entity("GymManager.DbModels.EntryRegistry", b =>
                {
                    b.HasOne("GymManager.DbModels.CabinetKey", "CabinetKey")
                        .WithMany()
                        .HasForeignKey("CabinetKeyID");

                    b.HasOne("GymManager.DbModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CabinetKey");

                    b.Navigation("Member");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("GymManager.DbModels.Identifier", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.MediaCarrier", "MediaCarrier")
                        .WithMany()
                        .HasForeignKey("MediaCarrierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("AddedByUser");

                    b.Navigation("MediaCarrier");

                    b.Navigation("Member");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("GymManager.DbModels.Member", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID");

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("GymManager.DbModels.Pass", "Pass")
                        .WithMany()
                        .HasForeignKey("PassID");

                    b.Navigation("AddedByUser");

                    b.Navigation("Gender");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Pass");
                });

            modelBuilder.Entity("GymManager.DbModels.Message", b =>
                {
                    b.HasOne("GymManager.DbModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymManager.DbModels.Pass", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("GymManager.DbModels.PassTime", "PassTime")
                        .WithMany()
                        .HasForeignKey("PassTimeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.Tax", "Tax")
                        .WithMany()
                        .HasForeignKey("TaxID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("PassTime");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("GymManager.DbModels.PassRegistry", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("GymManager.DbModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("GymManager.DbModels.Pass", "Pass")
                        .WithMany()
                        .HasForeignKey("PassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Member");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Pass");
                });

            modelBuilder.Entity("GymManager.DbModels.User", b =>
                {
                    b.HasOne("GymManager.DbModels.User", "ModifiedByUser")
                        .WithOne("AddedByUser")
                        .HasForeignKey("GymManager.DbModels.User", "ModifiedBy");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("GymManager.DbModels.User", b =>
                {
                    b.Navigation("AddedByUser");
                });
#pragma warning restore 612, 618
        }
    }
}
